namespace Core;

public enum BindingID
{
    None = 0,

    // Movement
    MOVEFORWARD,
    MOVEBACKWARD,
    STRAFELEFT,
    STRAFERIGHT,
    JUMP,
    TURNLEFT,
    TURNRIGHT,
    TURNORACTION,
    MOVEANDSTEER,
    TOGGLEAUTORUN,
    TOGGLERUN,
    SITORSTAND,
    DISMOUNT,

    // Targeting
    TARGETSELF,
    TARGETNEAREST,
    TARGETNEARESTENEMY,
    TARGETNEARESTENEMYPLAYER,
    TARGETNEARESTFRIEND,
    TARGETNEARESTFRIENDPLAYER,
    TARGETPREVIOUS,
    TARGETPREVIOUSENEMY,
    TARGETPREVIOUSENEMYPLAYER,
    TARGETPREVIOUSFRIEND,
    TARGETPREVIOUSFRIENDPLAYER,
    TARGETMOUSEOVER,
    TARGETFOCUS,
    TARGETTALKER,
    TARGETLASTHOSTILE,
    TARGETLASTTARGET,
    ASSISTTARGET,
    TARGETPET,
    TARGETPARTYMEMBER1,
    TARGETPARTYMEMBER2,
    TARGETPARTYMEMBER3,
    TARGETPARTYMEMBER4,
    TARGETPARTYPET1,
    TARGETPARTYPET2,
    TARGETPARTYPET3,
    TARGETPARTYPET4,

    // Combat
    ATTACKTARGET,
    STARTATTACK,
    STOPATTACK,
    STOPCASTING,
    PETATTACK,

    // Interaction
    INTERACTTARGET,
    INTERACTMOUSEOVER,
    FOLLOWTARGET,

    // UI Toggles
    TOGGLEACTIONBARLOCK,
    TOGGLEAUTORUN2,
    TOGGLEBACKPACK,
    OPENALLBAGS,
    TOGGLECHARACTER0,
    TOGGLESPELLBOOK,
    TOGGLETALENTS,
    TOGGLEQUESTLOG,
    TOGGLEWORLDMAP,
    TOGGLEGAMEMENU,
    TOGGLEMINIMAP,
    TOGGLEMOUNTJOURNAL,
    TOGGLEPETJOURNAL,
    TOGGLEACHIEVEMENT,
    TOGGLEENCOUNTERJOURNAL,
    TOGGLECURRENCY,
    TOGGLESTATISTICS,

    // Action Bar - Main (slots 1-12)
    ACTIONBUTTON1,
    ACTIONBUTTON2,
    ACTIONBUTTON3,
    ACTIONBUTTON4,
    ACTIONBUTTON5,
    ACTIONBUTTON6,
    ACTIONBUTTON7,
    ACTIONBUTTON8,
    ACTIONBUTTON9,
    ACTIONBUTTON10,
    ACTIONBUTTON11,
    ACTIONBUTTON12,

    // Action Bar - Bottom Left (slots 61-72)
    MULTIACTIONBAR1BUTTON1,
    MULTIACTIONBAR1BUTTON2,
    MULTIACTIONBAR1BUTTON3,
    MULTIACTIONBAR1BUTTON4,
    MULTIACTIONBAR1BUTTON5,
    MULTIACTIONBAR1BUTTON6,
    MULTIACTIONBAR1BUTTON7,
    MULTIACTIONBAR1BUTTON8,
    MULTIACTIONBAR1BUTTON9,
    MULTIACTIONBAR1BUTTON10,
    MULTIACTIONBAR1BUTTON11,
    MULTIACTIONBAR1BUTTON12,

    // Action Bar - Bottom Right (slots 49-60)
    MULTIACTIONBAR2BUTTON1,
    MULTIACTIONBAR2BUTTON2,
    MULTIACTIONBAR2BUTTON3,
    MULTIACTIONBAR2BUTTON4,
    MULTIACTIONBAR2BUTTON5,
    MULTIACTIONBAR2BUTTON6,
    MULTIACTIONBAR2BUTTON7,
    MULTIACTIONBAR2BUTTON8,
    MULTIACTIONBAR2BUTTON9,
    MULTIACTIONBAR2BUTTON10,
    MULTIACTIONBAR2BUTTON11,
    MULTIACTIONBAR2BUTTON12,

    // Shapeshift
    SHAPESHIFTBUTTON1,
    SHAPESHIFTBUTTON2,
    SHAPESHIFTBUTTON3,
    SHAPESHIFTBUTTON4,
    SHAPESHIFTBUTTON5,
    SHAPESHIFTBUTTON6,
    SHAPESHIFTBUTTON7,
    SHAPESHIFTBUTTON8,
    SHAPESHIFTBUTTON9,
    SHAPESHIFTBUTTON10,

    // Camera
    CAMERAZOOMIN,
    CAMERAZOOMOUT,
    FLIPCAMERAYAW,

    // Chat
    OPENCHAT,
    OPENCHATSLASH,
    REPLY,

    // Raid Markers
    RAIDTARGET1,
    RAIDTARGET2,
    RAIDTARGET3,
    RAIDTARGET4,
    RAIDTARGET5,
    RAIDTARGET6,
    RAIDTARGET7,
    RAIDTARGET8,
    RAIDTARGETNONE,

    // Nameplates
    NAMEPLATES,
    FRIENDNAMEPLATES,

    // Miscellaneous
    SCREENSHOT,
    TOGGLESHEATH,
    TOGGLEFPS,
    TOGGLEUI,

    // Custom actions (secure buttons, not WoW built-ins)
    CUSTOM_STOPATTACK,
    CUSTOM_CLEARTARGET,
    CUSTOM_CONFIG,
    CUSTOM_FLUSH,
}

public static class BindingID_Extension
{
    public static string ToStringF(this BindingID value) => value switch
    {
        BindingID.None => string.Empty,

        // Movement
        BindingID.MOVEFORWARD => nameof(BindingID.MOVEFORWARD),
        BindingID.MOVEBACKWARD => nameof(BindingID.MOVEBACKWARD),
        BindingID.STRAFELEFT => nameof(BindingID.STRAFELEFT),
        BindingID.STRAFERIGHT => nameof(BindingID.STRAFERIGHT),
        BindingID.JUMP => nameof(BindingID.JUMP),
        BindingID.TURNLEFT => nameof(BindingID.TURNLEFT),
        BindingID.TURNRIGHT => nameof(BindingID.TURNRIGHT),
        BindingID.TURNORACTION => nameof(BindingID.TURNORACTION),
        BindingID.MOVEANDSTEER => nameof(BindingID.MOVEANDSTEER),
        BindingID.TOGGLEAUTORUN => nameof(BindingID.TOGGLEAUTORUN),
        BindingID.TOGGLERUN => nameof(BindingID.TOGGLERUN),
        BindingID.SITORSTAND => nameof(BindingID.SITORSTAND),
        BindingID.DISMOUNT => nameof(BindingID.DISMOUNT),

        // Targeting
        BindingID.TARGETSELF => nameof(BindingID.TARGETSELF),
        BindingID.TARGETNEAREST => nameof(BindingID.TARGETNEAREST),
        BindingID.TARGETNEARESTENEMY => nameof(BindingID.TARGETNEARESTENEMY),
        BindingID.TARGETNEARESTENEMYPLAYER => nameof(BindingID.TARGETNEARESTENEMYPLAYER),
        BindingID.TARGETNEARESTFRIEND => nameof(BindingID.TARGETNEARESTFRIEND),
        BindingID.TARGETNEARESTFRIENDPLAYER => nameof(BindingID.TARGETNEARESTFRIENDPLAYER),
        BindingID.TARGETPREVIOUS => nameof(BindingID.TARGETPREVIOUS),
        BindingID.TARGETPREVIOUSENEMY => nameof(BindingID.TARGETPREVIOUSENEMY),
        BindingID.TARGETPREVIOUSENEMYPLAYER => nameof(BindingID.TARGETPREVIOUSENEMYPLAYER),
        BindingID.TARGETPREVIOUSFRIEND => nameof(BindingID.TARGETPREVIOUSFRIEND),
        BindingID.TARGETPREVIOUSFRIENDPLAYER => nameof(BindingID.TARGETPREVIOUSFRIENDPLAYER),
        BindingID.TARGETMOUSEOVER => nameof(BindingID.TARGETMOUSEOVER),
        BindingID.TARGETFOCUS => nameof(BindingID.TARGETFOCUS),
        BindingID.TARGETTALKER => nameof(BindingID.TARGETTALKER),
        BindingID.TARGETLASTHOSTILE => nameof(BindingID.TARGETLASTHOSTILE),
        BindingID.TARGETLASTTARGET => nameof(BindingID.TARGETLASTTARGET),
        BindingID.ASSISTTARGET => nameof(BindingID.ASSISTTARGET),
        BindingID.TARGETPET => nameof(BindingID.TARGETPET),
        BindingID.TARGETPARTYMEMBER1 => nameof(BindingID.TARGETPARTYMEMBER1),
        BindingID.TARGETPARTYMEMBER2 => nameof(BindingID.TARGETPARTYMEMBER2),
        BindingID.TARGETPARTYMEMBER3 => nameof(BindingID.TARGETPARTYMEMBER3),
        BindingID.TARGETPARTYMEMBER4 => nameof(BindingID.TARGETPARTYMEMBER4),
        BindingID.TARGETPARTYPET1 => nameof(BindingID.TARGETPARTYPET1),
        BindingID.TARGETPARTYPET2 => nameof(BindingID.TARGETPARTYPET2),
        BindingID.TARGETPARTYPET3 => nameof(BindingID.TARGETPARTYPET3),
        BindingID.TARGETPARTYPET4 => nameof(BindingID.TARGETPARTYPET4),

        // Combat
        BindingID.ATTACKTARGET => nameof(BindingID.ATTACKTARGET),
        BindingID.STARTATTACK => nameof(BindingID.STARTATTACK),
        BindingID.STOPATTACK => nameof(BindingID.STOPATTACK),
        BindingID.STOPCASTING => nameof(BindingID.STOPCASTING),
        BindingID.PETATTACK => nameof(BindingID.PETATTACK),

        // Interaction
        BindingID.INTERACTTARGET => nameof(BindingID.INTERACTTARGET),
        BindingID.INTERACTMOUSEOVER => nameof(BindingID.INTERACTMOUSEOVER),
        BindingID.FOLLOWTARGET => nameof(BindingID.FOLLOWTARGET),

        // UI Toggles
        BindingID.TOGGLEACTIONBARLOCK => nameof(BindingID.TOGGLEACTIONBARLOCK),
        BindingID.TOGGLEAUTORUN2 => nameof(BindingID.TOGGLEAUTORUN),
        BindingID.TOGGLEBACKPACK => nameof(BindingID.TOGGLEBACKPACK),
        BindingID.OPENALLBAGS => nameof(BindingID.OPENALLBAGS),
        BindingID.TOGGLECHARACTER0 => nameof(BindingID.TOGGLECHARACTER0),
        BindingID.TOGGLESPELLBOOK => nameof(BindingID.TOGGLESPELLBOOK),
        BindingID.TOGGLETALENTS => nameof(BindingID.TOGGLETALENTS),
        BindingID.TOGGLEQUESTLOG => nameof(BindingID.TOGGLEQUESTLOG),
        BindingID.TOGGLEWORLDMAP => nameof(BindingID.TOGGLEWORLDMAP),
        BindingID.TOGGLEGAMEMENU => nameof(BindingID.TOGGLEGAMEMENU),
        BindingID.TOGGLEMINIMAP => nameof(BindingID.TOGGLEMINIMAP),
        BindingID.TOGGLEMOUNTJOURNAL => nameof(BindingID.TOGGLEMOUNTJOURNAL),
        BindingID.TOGGLEPETJOURNAL => nameof(BindingID.TOGGLEPETJOURNAL),
        BindingID.TOGGLEACHIEVEMENT => nameof(BindingID.TOGGLEACHIEVEMENT),
        BindingID.TOGGLEENCOUNTERJOURNAL => nameof(BindingID.TOGGLEENCOUNTERJOURNAL),
        BindingID.TOGGLECURRENCY => nameof(BindingID.TOGGLECURRENCY),
        BindingID.TOGGLESTATISTICS => nameof(BindingID.TOGGLESTATISTICS),

        // Action Bars - Main
        BindingID.ACTIONBUTTON1 => nameof(BindingID.ACTIONBUTTON1),
        BindingID.ACTIONBUTTON2 => nameof(BindingID.ACTIONBUTTON2),
        BindingID.ACTIONBUTTON3 => nameof(BindingID.ACTIONBUTTON3),
        BindingID.ACTIONBUTTON4 => nameof(BindingID.ACTIONBUTTON4),
        BindingID.ACTIONBUTTON5 => nameof(BindingID.ACTIONBUTTON5),
        BindingID.ACTIONBUTTON6 => nameof(BindingID.ACTIONBUTTON6),
        BindingID.ACTIONBUTTON7 => nameof(BindingID.ACTIONBUTTON7),
        BindingID.ACTIONBUTTON8 => nameof(BindingID.ACTIONBUTTON8),
        BindingID.ACTIONBUTTON9 => nameof(BindingID.ACTIONBUTTON9),
        BindingID.ACTIONBUTTON10 => nameof(BindingID.ACTIONBUTTON10),
        BindingID.ACTIONBUTTON11 => nameof(BindingID.ACTIONBUTTON11),
        BindingID.ACTIONBUTTON12 => nameof(BindingID.ACTIONBUTTON12),

        // Action Bars - Bottom Left
        BindingID.MULTIACTIONBAR1BUTTON1 => nameof(BindingID.MULTIACTIONBAR1BUTTON1),
        BindingID.MULTIACTIONBAR1BUTTON2 => nameof(BindingID.MULTIACTIONBAR1BUTTON2),
        BindingID.MULTIACTIONBAR1BUTTON3 => nameof(BindingID.MULTIACTIONBAR1BUTTON3),
        BindingID.MULTIACTIONBAR1BUTTON4 => nameof(BindingID.MULTIACTIONBAR1BUTTON4),
        BindingID.MULTIACTIONBAR1BUTTON5 => nameof(BindingID.MULTIACTIONBAR1BUTTON5),
        BindingID.MULTIACTIONBAR1BUTTON6 => nameof(BindingID.MULTIACTIONBAR1BUTTON6),
        BindingID.MULTIACTIONBAR1BUTTON7 => nameof(BindingID.MULTIACTIONBAR1BUTTON7),
        BindingID.MULTIACTIONBAR1BUTTON8 => nameof(BindingID.MULTIACTIONBAR1BUTTON8),
        BindingID.MULTIACTIONBAR1BUTTON9 => nameof(BindingID.MULTIACTIONBAR1BUTTON9),
        BindingID.MULTIACTIONBAR1BUTTON10 => nameof(BindingID.MULTIACTIONBAR1BUTTON10),
        BindingID.MULTIACTIONBAR1BUTTON11 => nameof(BindingID.MULTIACTIONBAR1BUTTON11),
        BindingID.MULTIACTIONBAR1BUTTON12 => nameof(BindingID.MULTIACTIONBAR1BUTTON12),

        // Action Bars - Bottom Right
        BindingID.MULTIACTIONBAR2BUTTON1 => nameof(BindingID.MULTIACTIONBAR2BUTTON1),
        BindingID.MULTIACTIONBAR2BUTTON2 => nameof(BindingID.MULTIACTIONBAR2BUTTON2),
        BindingID.MULTIACTIONBAR2BUTTON3 => nameof(BindingID.MULTIACTIONBAR2BUTTON3),
        BindingID.MULTIACTIONBAR2BUTTON4 => nameof(BindingID.MULTIACTIONBAR2BUTTON4),
        BindingID.MULTIACTIONBAR2BUTTON5 => nameof(BindingID.MULTIACTIONBAR2BUTTON5),
        BindingID.MULTIACTIONBAR2BUTTON6 => nameof(BindingID.MULTIACTIONBAR2BUTTON6),
        BindingID.MULTIACTIONBAR2BUTTON7 => nameof(BindingID.MULTIACTIONBAR2BUTTON7),
        BindingID.MULTIACTIONBAR2BUTTON8 => nameof(BindingID.MULTIACTIONBAR2BUTTON8),
        BindingID.MULTIACTIONBAR2BUTTON9 => nameof(BindingID.MULTIACTIONBAR2BUTTON9),
        BindingID.MULTIACTIONBAR2BUTTON10 => nameof(BindingID.MULTIACTIONBAR2BUTTON10),
        BindingID.MULTIACTIONBAR2BUTTON11 => nameof(BindingID.MULTIACTIONBAR2BUTTON11),
        BindingID.MULTIACTIONBAR2BUTTON12 => nameof(BindingID.MULTIACTIONBAR2BUTTON12),

        // Shapeshift
        BindingID.SHAPESHIFTBUTTON1 => nameof(BindingID.SHAPESHIFTBUTTON1),
        BindingID.SHAPESHIFTBUTTON2 => nameof(BindingID.SHAPESHIFTBUTTON2),
        BindingID.SHAPESHIFTBUTTON3 => nameof(BindingID.SHAPESHIFTBUTTON3),
        BindingID.SHAPESHIFTBUTTON4 => nameof(BindingID.SHAPESHIFTBUTTON4),
        BindingID.SHAPESHIFTBUTTON5 => nameof(BindingID.SHAPESHIFTBUTTON5),
        BindingID.SHAPESHIFTBUTTON6 => nameof(BindingID.SHAPESHIFTBUTTON6),
        BindingID.SHAPESHIFTBUTTON7 => nameof(BindingID.SHAPESHIFTBUTTON7),
        BindingID.SHAPESHIFTBUTTON8 => nameof(BindingID.SHAPESHIFTBUTTON8),
        BindingID.SHAPESHIFTBUTTON9 => nameof(BindingID.SHAPESHIFTBUTTON9),
        BindingID.SHAPESHIFTBUTTON10 => nameof(BindingID.SHAPESHIFTBUTTON10),

        // Camera
        BindingID.CAMERAZOOMIN => nameof(BindingID.CAMERAZOOMIN),
        BindingID.CAMERAZOOMOUT => nameof(BindingID.CAMERAZOOMOUT),
        BindingID.FLIPCAMERAYAW => nameof(BindingID.FLIPCAMERAYAW),

        // Chat
        BindingID.OPENCHAT => nameof(BindingID.OPENCHAT),
        BindingID.OPENCHATSLASH => nameof(BindingID.OPENCHATSLASH),
        BindingID.REPLY => nameof(BindingID.REPLY),

        // Raid Markers
        BindingID.RAIDTARGET1 => nameof(BindingID.RAIDTARGET1),
        BindingID.RAIDTARGET2 => nameof(BindingID.RAIDTARGET2),
        BindingID.RAIDTARGET3 => nameof(BindingID.RAIDTARGET3),
        BindingID.RAIDTARGET4 => nameof(BindingID.RAIDTARGET4),
        BindingID.RAIDTARGET5 => nameof(BindingID.RAIDTARGET5),
        BindingID.RAIDTARGET6 => nameof(BindingID.RAIDTARGET6),
        BindingID.RAIDTARGET7 => nameof(BindingID.RAIDTARGET7),
        BindingID.RAIDTARGET8 => nameof(BindingID.RAIDTARGET8),
        BindingID.RAIDTARGETNONE => nameof(BindingID.RAIDTARGETNONE),

        // Nameplates
        BindingID.NAMEPLATES => nameof(BindingID.NAMEPLATES),
        BindingID.FRIENDNAMEPLATES => nameof(BindingID.FRIENDNAMEPLATES),

        // Miscellaneous
        BindingID.SCREENSHOT => nameof(BindingID.SCREENSHOT),
        BindingID.TOGGLESHEATH => nameof(BindingID.TOGGLESHEATH),
        BindingID.TOGGLEFPS => nameof(BindingID.TOGGLEFPS),
        BindingID.TOGGLEUI => nameof(BindingID.TOGGLEUI),

        // Custom actions
        BindingID.CUSTOM_STOPATTACK => nameof(BindingID.CUSTOM_STOPATTACK),
        BindingID.CUSTOM_CLEARTARGET => nameof(BindingID.CUSTOM_CLEARTARGET),
        BindingID.CUSTOM_CONFIG => nameof(BindingID.CUSTOM_CONFIG),
        BindingID.CUSTOM_FLUSH => nameof(BindingID.CUSTOM_FLUSH),

        _ => string.Empty
    };
}
